import invidiousAxios from '../invidiousAxios';
import type { TrackWithSave } from '../interfaces/track';
import type { Album } from '../interfaces/albums';
import type { Artist } from '../interfaces/artist';
import type { Playlist } from '../interfaces/playlists';

// Invidious API response interfaces
interface InvidiousVideo {
    type: 'video';
    title: string;
    videoId: string;
    author: string;
    authorId: string;
    videoThumbnails: Array<{
        quality: string;
        url: string;
        width: number;
        height: number;
    }>;
    lengthSeconds: number;
    viewCount: number;
    published: number;
    musicTracks?: Array<{
        song: string;
        artist: string;
        album?: string;
    }>;
}

interface InvidiousPlaylist {
    type: 'playlist';
    title: string;
    playlistId: string;
    author: string;
    authorId: string;
    playlistThumbnail?: string;
    videoCount: number;
}

interface InvidiousChannel {
    type: 'channel';
    author: string;
    authorId: string;
    authorThumbnails: Array<{
        url: string;
        width: number;
        height: number;
    }>;
    autoGenerated: boolean;
    subCount: number;
    videoCount: number;
    description: string;
    descriptionHtml: string;
}

// Convert Invidious video to Spotify-like track with save state
const convertVideoToTrackWithSave = (video: InvidiousVideo): TrackWithSave => {
    const musicTrack = video.musicTracks && video.musicTracks[0];

    const album: Album = {
        album_type: 'album',
        artists: [{
            id: video.authorId,
            name: musicTrack?.artist || video.author,
            type: 'artist',
            uri: `spotify:artist:${video.authorId}`,
            external_urls: {
                spotify: `https://music.youtube.com/channel/${video.authorId}`
            },
            href: `https://music.youtube.com/channel/${video.authorId}`,
        }],
        available_markets: [],
        external_urls: {
            spotify: `https://music.youtube.com/watch?v=${video.videoId}`
        },
        href: `https://music.youtube.com/watch?v=${video.videoId}`,
        id: `${video.videoId}-album`,
        images: video.videoThumbnails.map(thumb => ({
            url: thumb.url,
            height: thumb.height || 0,
            width: thumb.width || 0,
        })),
        name: musicTrack?.album || video.title,
        release_date: new Date().toISOString().split('T')[0],
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: `spotify:album:${video.videoId}-album`,
    };

    return {
        id: video.videoId,
        name: musicTrack?.song || video.title,
        artists: [{
            id: video.authorId,
            name: musicTrack?.artist || video.author,
            type: 'artist',
            uri: `spotify:artist:${video.authorId}`,
            external_urls: {
                spotify: `https://music.youtube.com/channel/${video.authorId}`
            },
            href: `https://music.youtube.com/channel/${video.authorId}`,
        }],
        album,
        duration_ms: video.lengthSeconds * 1000,
        popularity: Math.min(100, Math.floor(video.viewCount / 1000000)),
        preview_url: `https://yewtu.be/latest_version?id=${video.videoId}&itag=140`,
        track_number: 1,
        type: 'track',
        uri: `spotify:track:${video.videoId}`,
        external_urls: {
            spotify: `https://music.youtube.com/watch?v=${video.videoId}`
        },
        href: `https://music.youtube.com/watch?v=${video.videoId}`,
        explicit: false,
        available_markets: [],
        disc_number: 1,
        is_local: false,
        external_ids: {
            isrc: ''
        },
        is_playable: true,
        saved: false,
    };
};

// Convert Invidious playlist to Spotify-like playlist
const convertPlaylistToPlaylist = (playlist: InvidiousPlaylist): Playlist => {
    return {
        collaborative: false,
        description: '',
        external_urls: {
            spotify: `https://music.youtube.com/playlist?list=${playlist.playlistId}`
        },
        href: `https://music.youtube.com/playlist?list=${playlist.playlistId}`,
        id: playlist.playlistId,
        images: playlist.playlistThumbnail ? [{
            url: playlist.playlistThumbnail,
            height: 300,
            width: 300,
        }] : [
            { url: '', height: 300, width: 300 },
            { url: '', height: 300, width: 300 }
        ],
        followers: {
            href: '',
            total: 0,
        },
        name: playlist.title,
        owner: {
            id: playlist.authorId,
            display_name: playlist.author,
            type: 'user',
            uri: `spotify:user:${playlist.authorId}`,
            external_urls: {
                spotify: `https://music.youtube.com/channel/${playlist.authorId}`
            },
            href: `https://music.youtube.com/channel/${playlist.authorId}`,
            images: [
                { url: '', height: 300, width: 300 },
                { url: '', height: 300, width: 300 }
            ],
            followers: {
                href: null,
                total: 0,
            },
        },
        public: true,
        snapshot_id: playlist.playlistId,
        tracks: {
            href: `https://music.youtube.com/playlist?list=${playlist.playlistId}`,
            total: playlist.videoCount,
        },
        type: 'playlist',
        uri: `spotify:playlist:${playlist.playlistId}`,
    };
};

// Convert Invidious channel to Spotify-like artist
const convertChannelToArtist = (channel: InvidiousChannel): Artist => {
    return {
        id: channel.authorId,
        name: channel.author,
        genres: ['music'],
        images: channel.authorThumbnails.map(thumb => ({
            url: thumb.url,
            height: thumb.height || 0,
            width: thumb.width || 0,
        })),
        popularity: Math.min(100, Math.floor(channel.subCount / 10000)),
        type: 'artist',
        uri: `spotify:artist:${channel.authorId}`,
        external_urls: {
            spotify: `https://music.youtube.com/channel/${channel.authorId}`
        },
        href: `https://music.youtube.com/channel/${channel.authorId}`,
        followers: {
            href: '',
            total: channel.subCount,
        },
    };
};

/**
 * @description Search YouTube Music content using Invidious API
 */
export const querySearch = async (params: {
    q: string;
    type: string;
    limit?: number;
    offset?: number;
}) => {
    try {
        // Map Spotify types to Invidious search types
        let searchType = 'all';
        if (params.type.includes('track') || params.type.includes('video')) {
            searchType = 'video';
        } else if (params.type.includes('playlist')) {
            searchType = 'playlist';
        } else if (params.type.includes('artist') || params.type.includes('channel')) {
            searchType = 'channel';
        }

        const response = await invidiousAxios.get<any[]>(`/api/v1/search`, {
            params: {
                q: params.q,
                type: searchType,
                page: params.offset ? Math.floor(params.offset / (params.limit || 20)) + 1 : 1,
                limit: params.limit || 20,
            },
        });

        // Initialize empty arrays for each type
        const tracks: TrackWithSave[] = [];
        const albums: Album[] = [];
        const artists: Artist[] = [];
        const playlists: Playlist[] = [];

        // Process the results based on their type
        response.data.forEach((item: any) => {
            switch (item.type) {
                case 'video':
                    tracks.push(convertVideoToTrackWithSave(item));
                    break;
                case 'playlist':
                    playlists.push(convertPlaylistToPlaylist(item));
                    break;
                case 'channel':
                    artists.push(convertChannelToArtist(item));
                    break;
            }
        });

        return {
            albums: {
                href: '',
                items: albums,
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: albums.length,
            },
            tracks: {
                href: '',
                items: tracks,
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: tracks.length,
            },
            artists: {
                href: '',
                items: artists,
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: artists.length,
            },
            playlists: {
                href: '',
                items: playlists,
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: playlists.length,
            },
        };
    } catch (error) {
        console.error('Invidious search error:', error);
        // Return empty results in case of error
        return {
            albums: {
                href: '',
                items: [],
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: 0,
            },
            tracks: {
                href: '',
                items: [],
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: 0,
            },
            artists: {
                href: '',
                items: [],
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: 0,
            },
            playlists: {
                href: '',
                items: [],
                limit: params.limit || 20,
                next: '',
                offset: params.offset || 0,
                previous: '',
                total: 0,
            },
        };
    }
};